### ISSUE TITLE
你好这个问题怎么回答

### ISSUE THREAD

**Issue by yangninghua** [HarleysZhang/2021_algorithm_intern_information#1]
离线过采样和在线过采样哪个更快？

**Comment by harleyszhang** [comment]
我觉得是小数据离线过采样更快，大数据集差不多，但是为了方便，大数据集一般都是用在线过线采样

**Comment by xxllp** [comment]
现在实习竞争压力这么大吗

**Comment by harleyszhang** [comment]
😂一年比一年难啊，我写在这上面的题目都是最基础的了。

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by xxllp** [comment]
怪不得，人多了企业需求反而少了

**Comment by harleyszhang** [comment]
恩恩，是啊，一起加油吧
