### ISSUE TITLE
关于公式的显示问题

### ISSUE THREAD

**Issue by luqioayun** [HarleysZhang/2021_algorithm_intern_information#6]
您好，非常感谢您的分享，提供了很好的指导；公式显示貌似有些问题（我试过的浏览器包括Google Chrome、Firefox）
例如[神经网络模型复杂度分析的公式](https://github.com/HarleysZhang/2020_algorithm_intern_information/blob/master/%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0/%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C%E6%A8%A1%E5%9E%8B%E5%A4%8D%E6%9D%82%E5%BA%A6%E5%88%86%E6%9E%90.md)显示如下：
![image](https://user-images.githubusercontent.com/39177525/99493180-bc485180-29a9-11eb-86ea-c518a04e5fbc.png)

**Comment by harleyszhang** [comment]
可以下载 MathJax Plugin for Github 这个谷歌插件，或者下载我的项目后用typora阅读

**Comment by luqioayun** [comment]
> 可以下载 MathJax Plugin for Github 这个谷歌插件，或者下载我的项目后用typora阅读
感谢~ got it~
